import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import { fetchItems, addItem, updateItem, deleteItem } from "./cartAPI";

const initialState = {
  items: [],
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action. This will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

// fetch all items
export const fetchCartAsync = createAsyncThunk("cart/fetchItems", async () => {
  const response = await fetchItems();
  return response.data;
});

// Add a new item
export const addAsync = createAsyncThunk("cart/addItem", async (item) => {
  const { product_id, title, price, thumbnail } = item;
  const response = await addItem({
    product_id,
    title,
    price,
    thumbnail,
    quantity: 1,
  });
  return response.data;
});

// Delete an item
export const deleteAsync = createAsyncThunk("cart/deleteItem", async (id) => {
  await deleteItem(id);
  return id;
});

// slice
export const cartSlice = createSlice({
  name: "cart",
  initialState,
  reducers: {
    IncreaseInCart: (state, action) => {
      const id = action.payload;
      const itemIndex = state.items.findIndex((item) => item.id === id);
      state.items[itemIndex].quantity += 1;
    },

    DecreaseFromCart: (state, action) => {
      const id = action.payload;
      const itemIndex = state.items.findIndex((item) => item.id === id);
      if (state.items[itemIndex].quantity > 1)
        state.items[itemIndex].quantity -= 1;
    },
    // your reducer functions here
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchCartAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.items = action.payload;
      })
      .addCase(addAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.items.push(action.payload);
      })
      .addCase(deleteAsync.fulfilled, (state, action) => {
        state.status = "idle";
        const id = action.payload;
        const index = state.items.findIndex((item) => item.id === id);
        state.items.splice(index, 1);
      });
  },
});

export const { IncreaseInCart, DecreaseFromCart } = cartSlice.actions;
export default cartSlice.reducer;
